# Generated by Django 2.0.7 on 2019-02-03 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20190203_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
